### ISSUE TITLE
Additional iOS apps

### ISSUE THREAD

**Issue by pawalan** [YOURLS/awesome-yourls#38]
Hi folks,
found out about https://shortmenu.com/ today.
Given you are willing to pay a small fee for the in-app purchase "Own Services", ShortMenu makes it a snap to support YourLS. Compared to the other iOS apps (like Yourls Shortener, ShortFox and Arrgly), ShortMenu brings Sharesheets (quick and custom) which make it really usable.
Maybe ShortMenu and the other apps mentioned should be added to this list.

**Comment by LeoColomb** [comment]
Sure! Happy to include it!
Just be sure to precise the service is commercial.

**Comment by pawalan** [comment]
Hi Leo,

the app itself is free of charge, however you can't configure your own 
services in the basic version.
Like, you cant query your own app's API (e.g. Yourls).

If you do an in-app purchase of about 3€, this feature gets enabled.
Then you can add your own APIs - so also YourLS.
They even have a dedicated HowTo for YourLS on their webpage:
https://shortmenu.com/support/custom-services/yourls/

All the best and thank you for this awesome collection - happy to 
contribute.

     Sven.

ps: I am in no way affiliated with the company, I just find the app 
really useful!

----------------------------------
Sven Göttner
Diepolz 32
D-87509 Immenstadt
MOBIL +49(0)177/4923288
MAIL  post@sven-goettner.de

------ Originalnachricht ------
Von: "Léo Colombaro" <notifications@github.com>
An: "YOURLS/awesome-yourls" <awesome-yourls@noreply.github.com>
Cc: "Sven Göttner" <post@sven-goettner.de>; "Author" 
<author@noreply.github.com>
Gesendet: 26.03.2019 12:57:32
Betreff: Re: [YOURLS/awesome-yourls] Additional iOS apps (#38)

**Comment by LeoColomb** [comment]
Can you open a PR with that addition? @pawalan 
This is a required step to get it listed! 🙂

**Comment by pawalan** [comment]
Dear Leo, I am just getting familiar with Git/GitHub these days and haven't contributed to any project yet.
Could you maybe tell me what exactly to do in order to contribute my suggestions to the list or point me to a resource from which I can learn by myself?
Thanks!

**Comment by LeoColomb** [comment]
Sure!
Adding an item in a text file on GitHub is very easy. See [GitHub Help article](https://help.github.com/en/articles/editing-files-in-another-users-repository) on how to make a file edition on GitHub.

The relevant file in our case is the [README.md](https://github.com/YOURLS/awesome-yourls/blob/master/README.md).

More generally, you can read [Open Source Guides](https://opensource.guide/) as a starting point for your open-source contribution.

**Comment by andrewjmetzger** [comment]
@LeoColomb PR submitted, see #41.
