### ISSUE TITLE
another android app (aYourls)

### ISSUE THREAD

**Issue by NewRedsquare** [YOURLS/awesome-yourls#53]
Hello,

you recently added an android app into the list, but i've found an alternative that supports server url deletion too :D https://apkpure.com/ayourls/de.mateware.ayourls. Saldy it's not on play store anymore but i use and it. It works very well.

**Comment by ozh** [comment]
Seems to be also available at https://gitlab.com/matecode/ayourls, I'd rather add that link instead of the apkpure one. Fancy a pull request to add it to the list?

**Comment by NewRedsquare** [comment]
PR done.
