### ISSUE TITLE
Add Change-Title Plugin

### ISSUE THREAD

**Issue by Juliaria08** [YOURLS/awesome-yourls#95]
* [X] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [X] This request isn't a duplicate of an existing request
* [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions)

**Summary**

Can we add [Change-Title plugin](https://happier.allowed.org/change-title)?

**Motivation**

So some pepole can change the title

**Is your feature request related to a problem? Please describe.**

I'd like my plugin be added.

**Describe the solution you'd like**

Adding my plugin

**Describe alternatives you've considered**

¿Not adding it?

**Additional context**

I have made a plugin didn't you know, as i am doing bad by editing the template i wont remove it so

**Comment by dgw** [comment]
I don't quite understand what the plugin does, but you're welcome to open a pull request that adds it to the list.

**Comment by Juliaria08** [comment]
> I don't quite understand what the plugin does, but you're welcome to open a pull request that adds it to the list.

It changes the <title> tag

**Comment by Juliaria08** [comment]
@dgw I have done it #96
